### PR TITLE
Use goroutines for each license and add features aggregate expiration

### PR DESCRIPTION
**Pull request by treydock**
Main change was to execute each license collection in parallel using goroutines. Also add metric to indicate if failures occurred during collection.

Added metric `flexlm_feature_aggregate_expiration_seconds` that groups features for a license by expiration times. I use this in an alert so that if a license has 25 features expiring soon we only get 1 alert and not 25 alerts.

The diff is not as big if you use something like `git diff -w` to remove whitespace changes.

Alert we are using:

```
  rules:
  - record: flexlm_feature_aggregate_expiration_days
    expr: (flexlm_feature_aggregate_expiration_seconds - time()) / 86400
  - alert: LicenseExpiring
    expr: flexlm_feature_aggregate_expiration_days < 14
    for: 5m
    labels:
      notify: daily
      alertgroup: licenses
      severity: warning
      alsonotify: license-admins
    annotations:
      title: License {{ $labels.license }} expiring soon on {{ $labels.host }}
      description: License {{ $labels.license }} on {{ $labels.host }} has {{ $labels.features }} features ({{ $labels.licenses }} licenses) expiring in {{ $value }} days
```

### CODE REVIEW

**Comment by mjtrangoni** [comment]
Hi @treydock,

Thanks for your PR! Could you please take a look at the linter errors? I will be checking your PR at weekend.

**Comment by treydock** [comment]
Fixed lint issues. Had to increase dupl to threshold of 200 because it kept saying 2 functions were identical when they were not identical.  If want to keep threshold at 100 I could add an ignore comment instead.

**Comment by mjtrangoni** [comment]
LGTM. Thanks again for your PR!

Could you please also add your additional rules for the Alert Manager [here](https://github.com/mjtrangoni/flexlm_exporter#prometheus-rules)?

**Comment by treydock** [comment]
I may need to adjust the way aggregate labels are done. I ran into issue where the `index` label kept changing so alerts began to flap.

I'll update PR with a fix once I've verified it on my end and will also update README with alert examples

**Comment by treydock** [comment]
Don't know if the right solution but am sorting the aggregate expirations to hopefully avoid labels from switching back and forth. Ran into issue where expired license and new license kept flipping between different index numbers and this resulted in lots of alerts / resolutions.

Also added README example of alert I'm using for expiration.

**Comment by treydock** [comment]
This should be good to merge if everything looks good. I have been running this PR on our systems for a bit now and everything is working as expected.

**Comment by mjtrangoni** [comment]
@treydock thanks!

**Pull request merged**
